apiVersion: v1
kind: Service
metadata:
  name: jakartaee-k8s-hello-world-service
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32760
  selector:
      app: jakartaee-k8s-hello-world
      environment: production